language: cpp

before_script:
  - sudo apt-get install libboost-test-dev -y
  - sudo apt-get install libgtest-dev -y
  - mkdir gbuild; cd gbuild
  - cmake -DBUILD_SHARED_LIBS=ON /usr/src/gtest
  - cmake --build .
  - cmake --build . --target install
  - cd ..

script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package

deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T helloworld-1.0.$TRAVIS_BUILD_NUMBER.deb -uansochnev:$BINTRAY_API_KEY "https://api.bintray.com/content/ansochnev/otus-cpp/helloworld/$TRAVIS_BUILD_NUMBER/pool/main/h1/helloworld-1.0.$TRAVIS_BUILD_NUMBER.deb;deb_distribution=homework;deb_component=main;deb_architecture=amd64;publish=1"
